# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Joseph Nguyen
title: New Graduate Software Engineer
email: contact@josephnguyen.io
phone: (601) 397-8635
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyll
github_username:  JosephNguyenDev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: joseph-nguyen-81964812a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Joseph, but everyone calls me Joe. I recently graduated from the University of California - San Diego, and I am looking for an entry level position as either a Full Stack engineer or a Backend engineer. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ISA McISAface
        link: https://github.com/jonguyen-ucsd/141
        # link_text: Project Website
        additional_links:
          - title:  9-bit intstruction set Architecture
            icon: fab fa-github
            url: https://github.com/jonguyen-ucsd/141
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          In this project, my team and I were challenged to create an instruction set architecture with only 9 bits to encode an instruction. We decided on a pseudo-accumulator/aggregator design which allowed us the flexibility of using 16 registers, and 20 instructions without sacrificing the amount of bits we could use for immediate values. We then designed a CPU that was able to accept our assembly language in <mark>System Verilog</mark>. I am proud to say that I wrote the assembler myself in <mark>python</mark>, which allowed us the additional flexibility of being able to use aliases in our language as well as support for instruction jumping.
      - layout: top-middle
        title: Walk Walk Revolution
        description: |
          For this project, my team created an <mark>Android</mark> app that allowed users to track steps and share walk and route data. This project allowed me to gain experience with the entire software development process from end to finish. I learned skills such as <mark>Software Design Principles</mark> and <mark>Agile Methodologies</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imgur
        link: Imgur.com
        sub_title: Software Engineer Intern
        caption: July 2020 - August 2020
        quote: >
          Magic of the Internet
        description: | # this will include new lines to allow paragraphs
          During my second Software Engineering internship, I was honored to work on Imgur's newest product, Melee, which is a platform for gamers to share gaming content and gaming related news. I worked on Melee's admin panel using <mark>Typescript</mark> and <mark>Reactjs</mark> for the front end as well as creating and maintaining API endpoints for it using <mark>Golang</mark> for the backend. 

      - layout: left
        sub_title: Software Engineer Intern
        caption: July 2019 - September 2019
        link: Imgur.com
        description: | # this will include new lines to allow paragraphs
          During my first Software Engineering internship, I came in during a time where Imgur needed to change out microservices. This effectively gave me experience in software integegration. My duties included
          - Working in <mark>Golang</mark> and <mark>PHP</mark> on a microservice-based backend using <mark>RESTful</mark> api practices
          - Conducting research and assisted in the migration from a now defunct microservice to a new replacement microservice
          - Coordinating with multiple engineering teams to maintain and develop code to be used across Imgur's platforms
          - Troubleshoot and fix reported bugs/vulnerabilities
          
      - layout: left
        sub_title: Software Quality Assurance Intern
        caption: July 2019 - September 2019
        link: Imgur.com
        description: | # this will include new lines to allow paragraphs
          During my first internship with Imgur, I worked with multiple engineering teams as well as the community and product teams to maintain the quality of Imgur's products. Some of my duties included
          - Investigating Imgur's products for deficiencies and suggesting solutions for product problems
          - Plan, create, and manage quality planning strategies
          - Collect and record quality data for engineering team use
          - Prepare and present reports and metrics to Senior Management

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, San Diego
        caption: 2018 - 2021
        sub_title: BS Computer Science

  - title: Languages Used
    layout: text
    content: |
      - Java
      - C++
      - Golang
      - PHP
      - Typescript
      - Javascript
      - Reactjs
      - postgreSQL
      - Kotlin
  
  - title: Skills
    layout: text
    content: |
      - Object Oriented Programming concepts
      - Knowledge of Advanced Data Structures and Algorithms
      - Agile Methodologies
      - REST
      - Google Protocol Buffers
      - gRPC
      - Android App development

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering and networking, some of my other interests and hobbies are:
      - Weight Lifting
      - Ring Gymnastics
      - Magic the Gathering
      - Tabletop Games
      - Various Video Games


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
